apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
  labels:
    app: dashapp
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      app: dashapp
  template:
    metadata:
      labels:
        app: dashapp
    spec:
      {{- if .Values.postgresql.primary.nodeSelector }}
      nodeSelector: {{ .Values.postgresql.primary.nodeSelector | toJson }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: dashapp
          image: "{{.Values.image.registry}}/{{.Values.image.repository}}:{{.Values.image.tag}}"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: {{.Values.resources.requests.cpu}}
              memory: {{.Values.resources.requests.memory}}
            limits:
            {{- if not (empty .Values.resources.limits.cpu) }}
              cpu: {{.Values.resources.limits.cpu}}
            {{- end }}
            {{- if not (empty .Values.resources.limits.memory) }}
              memory: {{.Values.resources.limits.memory}}
            {{- end }}
          envFrom:
            - configMapRef:
                name: dashapp
          {{- if not (empty .Values.config.secretRef) }}
            - secretRef:
                name: {{ .Values.config.secretRef }}
          {{- end }}
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: dash-config
              mountPath: /app/dash-config.yaml
              subPath: dashConfig
          {{- if .Values.database.auth.sslRootCert.secretName }}
            - name: db-ca-cert
              mountPath: /app/certs
              readOnly: true
          {{- end }}
      volumes:
        - name: dash-config
          configMap:
            name: dashapp
        {{- if .Values.database.auth.sslRootCert.secretName }}
        - name: db-ca-cert
          secret:
            secretName: {{ .Values.database.auth.sslRootCert.secretName }}
            items:
              - key: {{ .Values.database.auth.sslRootCert.key }}
                path: rds-combined-ca-bundle.pem
        {{- end }}

