apiVersion: v1
kind: Service
metadata:
  name: dashapp
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  selector:
    app: dashapp
  ports:
    - name: http
      port: 3000
      targetPort: 3000